[dependencies]
open-modular-engine.workspace             = true
open-modular-module-gen.workspace         = true
open-modular-module-io.workspace          = true
open-modular-module-util.workspace        = true
open-modular-runtime.workspace            = true
open-modular-runtime-production.workspace = true
tracing.workspace                         = true
tracing-subscriber.workspace              = true
uuid.workspace                            = true

[lints]
workspace = true

[package]
authors.workspace    = true
categories.workspace = true
description          = "Open Modular Workbench"
edition.workspace    = true
keywords.workspace   = true
license.workspace    = true
name                 = "open-modular-workbench"
readme.workspace     = true
repository.workspace = true
version.workspace    = true
